// Code generated by goyacc -o eml_parser.go -p eml eml.y. DO NOT EDIT.

//line eml.y:2
package parser

import __yyfmt__ "fmt"

//line eml.y:2

import (
	"eml-parser/ast"
	"eml-parser/token"
)

//line eml.y:10
type emlSymType struct {
	yys  int
	tok  token.Token
	expr ast.Expr
}

const IDENT = 57346
const ONE = 57347
const EML = 57348
const LPAREN = 57349
const RPAREN = 57350
const COMMA = 57351
const ILLEGAL = 57352

var emlToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"ONE",
	"EML",
	"LPAREN",
	"RPAREN",
	"COMMA",
	"ILLEGAL",
}

var emlStatenames = [...]string{}

const emlEofCode = 1
const emlErrCode = 2
const emlInitialStackSize = 16

//line eml.y:51

//line yacctab:1
var emlExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const emlPrivate = 57344

const emlLast = 10

var emlAct = [...]int8{
	2, 8, 10, 4, 3, 5, 1, 7, 6, 9,
}

var emlPact = [...]int16{
	-1, -1000, -1000, -1000, -1000, 1, -1, -8, -1, -6,
	-1000,
}

var emlPgo = [...]int8{
	0, 6, 0,
}

var emlR1 = [...]int8{
	0, 1, 2, 2, 2,
}

var emlR2 = [...]int8{
	0, 1, 1, 1, 6,
}

var emlChk = [...]int16{
	-1000, -1, -2, 5, 4, 6, 7, -2, 9, -2,
	8,
}

var emlDef = [...]int8{
	0, -2, 1, 2, 3, 0, 0, 0, 0, 0,
	4,
}

var emlTok1 = [...]int8{
	1,
}

var emlTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10,
}

var emlTok3 = [...]int8{
	0,
}

var emlErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	emlDebug        = 0
	emlErrorVerbose = false
)

type emlLexer interface {
	Lex(lval *emlSymType) int
	Error(s string)
}

type emlParser interface {
	Parse(emlLexer) int
	Lookahead() int
}

type emlParserImpl struct {
	lval  emlSymType
	stack [emlInitialStackSize]emlSymType
	char  int
}

func (p *emlParserImpl) Lookahead() int {
	return p.char
}

func emlNewParser() emlParser {
	return &emlParserImpl{}
}

const emlFlag = -1000

func emlTokname(c int) string {
	if c >= 1 && c-1 < len(emlToknames) {
		if emlToknames[c-1] != "" {
			return emlToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func emlStatname(s int) string {
	if s >= 0 && s < len(emlStatenames) {
		if emlStatenames[s] != "" {
			return emlStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func emlErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !emlErrorVerbose {
		return "syntax error"
	}

	for _, e := range emlErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + emlTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(emlPact[state])
	for tok := TOKSTART; tok-1 < len(emlToknames); tok++ {
		if n := base + tok; n >= 0 && n < emlLast && int(emlChk[int(emlAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if emlDef[state] == -2 {
		i := 0
		for emlExca[i] != -1 || int(emlExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; emlExca[i] >= 0; i += 2 {
			tok := int(emlExca[i])
			if tok < TOKSTART || emlExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if emlExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += emlTokname(tok)
	}
	return res
}

func emllex1(lex emlLexer, lval *emlSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(emlTok1[0])
		goto out
	}
	if char < len(emlTok1) {
		token = int(emlTok1[char])
		goto out
	}
	if char >= emlPrivate {
		if char < emlPrivate+len(emlTok2) {
			token = int(emlTok2[char-emlPrivate])
			goto out
		}
	}
	for i := 0; i < len(emlTok3); i += 2 {
		token = int(emlTok3[i+0])
		if token == char {
			token = int(emlTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(emlTok2[1]) /* unknown char */
	}
	if emlDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", emlTokname(token), uint(char))
	}
	return char, token
}

func emlParse(emllex emlLexer) int {
	return emlNewParser().Parse(emllex)
}

func (emlrcvr *emlParserImpl) Parse(emllex emlLexer) int {
	var emln int
	var emlVAL emlSymType
	var emlDollar []emlSymType
	_ = emlDollar // silence set and not used
	emlS := emlrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	emlstate := 0
	emlrcvr.char = -1
	emltoken := -1 // emlrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		emlstate = -1
		emlrcvr.char = -1
		emltoken = -1
	}()
	emlp := -1
	goto emlstack

ret0:
	return 0

ret1:
	return 1

emlstack:
	/* put a state and value onto the stack */
	if emlDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", emlTokname(emltoken), emlStatname(emlstate))
	}

	emlp++
	if emlp >= len(emlS) {
		nyys := make([]emlSymType, len(emlS)*2)
		copy(nyys, emlS)
		emlS = nyys
	}
	emlS[emlp] = emlVAL
	emlS[emlp].yys = emlstate

emlnewstate:
	emln = int(emlPact[emlstate])
	if emln <= emlFlag {
		goto emldefault /* simple state */
	}
	if emlrcvr.char < 0 {
		emlrcvr.char, emltoken = emllex1(emllex, &emlrcvr.lval)
	}
	emln += emltoken
	if emln < 0 || emln >= emlLast {
		goto emldefault
	}
	emln = int(emlAct[emln])
	if int(emlChk[emln]) == emltoken { /* valid shift */
		emlrcvr.char = -1
		emltoken = -1
		emlVAL = emlrcvr.lval
		emlstate = emln
		if Errflag > 0 {
			Errflag--
		}
		goto emlstack
	}

emldefault:
	/* default state action */
	emln = int(emlDef[emlstate])
	if emln == -2 {
		if emlrcvr.char < 0 {
			emlrcvr.char, emltoken = emllex1(emllex, &emlrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if emlExca[xi+0] == -1 && int(emlExca[xi+1]) == emlstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			emln = int(emlExca[xi+0])
			if emln < 0 || emln == emltoken {
				break
			}
		}
		emln = int(emlExca[xi+1])
		if emln < 0 {
			goto ret0
		}
	}
	if emln == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			emllex.Error(emlErrorMessage(emlstate, emltoken))
			Nerrs++
			if emlDebug >= 1 {
				__yyfmt__.Printf("%s", emlStatname(emlstate))
				__yyfmt__.Printf(" saw %s\n", emlTokname(emltoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for emlp >= 0 {
				emln = int(emlPact[emlS[emlp].yys]) + emlErrCode
				if emln >= 0 && emln < emlLast {
					emlstate = int(emlAct[emln]) /* simulate a shift of "error" */
					if int(emlChk[emlstate]) == emlErrCode {
						goto emlstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if emlDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", emlS[emlp].yys)
				}
				emlp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if emlDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", emlTokname(emltoken))
			}
			if emltoken == emlEofCode {
				goto ret1
			}
			emlrcvr.char = -1
			emltoken = -1
			goto emlnewstate /* try again in the same state */
		}
	}

	/* reduction by production emln */
	if emlDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", emln, emlStatname(emlstate))
	}

	emlnt := emln
	emlpt := emlp
	_ = emlpt // guard against "declared and not used"

	emlp -= int(emlR2[emln])
	// emlp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if emlp+1 >= len(emlS) {
		nyys := make([]emlSymType, len(emlS)*2)
		copy(nyys, emlS)
		emlS = nyys
	}
	emlVAL = emlS[emlp+1]

	/* consult goto table to find next state */
	emln = int(emlR1[emln])
	emlg := int(emlPgo[emln])
	emlj := emlg + emlS[emlp].yys + 1

	if emlj >= emlLast {
		emlstate = int(emlAct[emlg])
	} else {
		emlstate = int(emlAct[emlj])
		if int(emlChk[emlstate]) != -emln {
			emlstate = int(emlAct[emlg])
		}
	}
	// dummy call; replaced with literal code
	switch emlnt {

	case 1:
		emlDollar = emlS[emlpt-1 : emlpt+1]
//line eml.y:22
		{
			emlVAL.expr = emlDollar[1].expr
			emllex.(*parserDriver).result = emlDollar[1].expr
		}
	case 2:
		emlDollar = emlS[emlpt-1 : emlpt+1]
//line eml.y:29
		{
			emlVAL.expr = ast.One{Span: toASTSpan(emlDollar[1].tok.Span)}
		}
	case 3:
		emlDollar = emlS[emlpt-1 : emlpt+1]
//line eml.y:33
		{
			emlVAL.expr = ast.Variable{
				Name: emlDollar[1].tok.Lexeme,
				Span: toASTSpan(emlDollar[1].tok.Span),
			}
		}
	case 4:
		emlDollar = emlS[emlpt-6 : emlpt+1]
//line eml.y:40
		{
			emlVAL.expr = ast.Apply{
				Left:  emlDollar[3].expr,
				Right: emlDollar[5].expr,
				Span: ast.Span{
					Start: toASTPosition(emlDollar[1].tok.Span.Start),
					End:   toASTPosition(emlDollar[6].tok.Span.End),
				},
			}
		}
	}
	goto emlstack /* stack new state and value */
}
